### ISSUE TITLE
SickRage -> SickChill

### ISSUE THREAD

**Issue by OmgImAlexis** [linuxserver/docker-sickrage#38]
Last time, sorry. ❤️ 

https://github.com/SickChill/SickChill

You can use https://github.com/SickChill/SickChill/issues/4984 to verify it's the same repo.

PING: @alex-phillips @CHBMB @sparklyballs

**Comment by miigotu** [comment]
Can you also rename the package? github will automatically redirect git clones and source/page urls.

**Comment by CHBMB** [comment]
@OmgImAlexis @miigotu We're going to migrate to a completely new sickchill repo and this current container has been deactivated in our build system.  So won't make further builds regardless of where the repo is pointed to.

**Comment by OmgImAlexis** [comment]
Sounds good.

**Comment by DanGarion** [comment]
How do I install via compose? When I try my normal way in portainer it craps out...

  sickchill:
    image: "linuxserver/docker-sickchill"
    container_name: "sickchill"
    volumes:
      - ${USERDIR}/docker/sickchill:/config
      - ${USERDIR}/docker/shared:/shared
    ports:
      - "8083:8081"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

**Comment by j0nnymoe** [comment]
Because the container hasn't been released yet.

**Comment by DanGarion** [comment]
That would be a great reason... Just started running into issues with my SickRage this week and everything started crapping out. The "new" version is terrible and SickBeard is basically crap to me. Never cared for Sonarr, so I'm in this holding pattern for now.

Thanks! :)

**Comment by jasker5183** [comment]
Any ETA for when container will be renamed?

**Comment by CHBMB** [comment]
> Any ETA for when container will be renamed?

When it's ready.

**Comment by miigotu** [comment]
@CHBMB We do have an official sickchill/sickchill:latest that is automatically built on push to master, at docker hub
We also have a docker-compose.yaml in our repo.

I think you could set up your FROM to be our base

**Comment by CHBMB** [comment]
Hey @miigotu that would be one way of doing things, but we were rather hoping to make it a bit more "special" with version control and multiarch which would be automatically be parsed from the docker manifest on the host machine.

That's why I asked @OmgImAlexis if you would be amenable to perhaps changing things upstream to mean we could produce some pretty nifty features in the new Sickchill container.  

We have already worked with the Sonarr and Ombi devs to begin implementing this and we've begin developing new containers using this method.  

Here's what I'm talking about with [Bazarr](https://hub.docker.com/r/linuxserver/bazarr/tags/), x64, ARMHF, and AARCH64 all on one repo, tags for each release, making version control easier if a user wants to pull a specific branch and a container for the development branch if people wish to run that.

Pretty sweet and was hoping we could do the same for SickChill.

We have a [Discord](https://discord.gg/YWrKVTn) channel if you want to chat some more about it with the guys who know a bit more about the pipeline stuff than me.  We can always set up a private Sickchill channel if you want to chat in private.

**Comment by miigotu** [comment]
@CHBMB Im up for that. I created a discord account, but I cant talk right now =P

**Comment by homerr** [comment]
Be good to see you in there so we can bounce some ideas around 👍
